# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
---
version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "📦 dependencies"
    assignees:
      - "kdeldycke"

  # XXX Dependabot does not update pinned reused workflows yet:
  # https://github.com/dependabot/dependabot-core/issues/4327
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "📦 dependencies"
    assignees:
      - "kdeldycke"
