---
- name: 🐛 bug
  color: "#FDC705"
  description: Something isn't working, or a fix is proposed

- name: 🎲 can't reproduce
  color: "#cfd3d7"
  description: Root cause not from project

- name: 🆙 changelog
  color: "#C2E0C6"
  description: Keep track of changes

- name: 👷 CI/CD
  color: "#A4A837"
  description: Tests, automation and management of the project

- name: 📦 dependencies
  color: "#AAA666"
  description: Update of dependencies

- name: 📗 documentation
  color: "#006b75"
  description: Update to non-code (readme, docstrings, typos, …)

- name: 🔄 duplicate
  color: "#cfd3d7"
  description: This issue or pull request already exists

- name: ✨ enhancement
  color: "#1870E3"
  description: Improvement or change to an existing feature

- name: 🆕 feature request
  color: "#84b6eb"
  description: Not existing yet and need to be implemented

- name: 🌱 good first issue
  color: "#B3CD7F"
  description: A place for newcomers to start contributing

- name: ℹ️ help wanted
  color: "#C2E0C6"
  description: Extra attention is needed

- name: ❓ question
  color: "#d876e3"
  description: Further information is requested

- name: 💣 security
  color: "#F83911"
  description: Exploit, token leaks, …

- name: 💖 sponsor
  color: "#D3B3F2"
  description: A sponsor is involved

- name: 🚫 wont do/fix
  color: "#cfd3d7"
  description: This will not be worked on