---
- name: ⚖️ curation
  color: "#d73a4a"
  description: Links or structure needs to be refined

- name: 🆕 new link
  color: "#fbca04"
  description: A link worth adding to the list

- name: 🩹 fix link
  color: "#d4c5f9"
  description: Existing link need to be updated
