name: Bug report
description: Report a bug in repomatic
labels: ["ðŸ› bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for reporting a bug! Before filing, please check if the issue
        is already fixed in the latest development version:


        ```shell-session

        $ uvx --from git+https://github.com/kdeldycke/repomatic -- repomatic --version

        ```


        If the bug is gone, it will be included in the next release.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: >
        Output of `repomatic --version` (or `uvx -- repomatic --version`).
      placeholder: "repomatic, version X.Y.Z"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: >
        Relevant log output. Run with `--verbosity DEBUG` for full details.
      render: text
