# Copyright Kevin Deldycke <kevin@deldycke.com> and contributors.
#
# This program is Free Software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

"""Unified tool runner with managed config resolution.

Provides ``repomatic run <tool>`` — a single entry point that installs an
external tool at a pinned version, resolves its configuration through a strict
4-level precedence chain, translates ``[tool.X]`` sections from
``pyproject.toml`` into the tool's native format, and invokes the tool with
the resolved config.

.. important::
    Config resolution precedence (first match wins, no merging):

    1. **Native config file** — tool's own config file in the repo.
    2. **``[tool.X]`` in ``pyproject.toml``** — translated to native format.
    3. **Bundled default** — from ``repomatic/data/``.
    4. **Bare invocation** — no config at all.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import subprocess
import sys
import tarfile
import tempfile
import zipfile
from contextlib import contextmanager, nullcontext
from dataclasses import dataclass, replace
from enum import Enum
from importlib.resources import as_file, files
from pathlib import Path, PurePosixPath
from urllib.request import Request, urlopen

import click
import tomlkit
import yaml
from extra_platforms import (
    AARCH64,
    ALL_PLATFORMS,
    LINUX,
    MACOS,
    WINDOWS,
    X86_64,
    Architecture,
    Group,
    Platform,
    current_architecture,
    current_platform,
    is_github_ci,
)

from .cache import get_cached_binary, store_binary
from .uv import uv_cmd, uvx_cmd

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib  # type: ignore[import-not-found]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from collections.abc import Callable, Iterator, Sequence
    from typing import Any, Literal

    from .metadata import Metadata


GENERATED_HEADER_TEMPLATE = (
    "Generated by {command} v{version} - https://github.com/kdeldycke/repomatic"
)
"""Template for the first line of generated-file headers.

Used by both CLI commands (e.g. ``sync-mailmap``) and the tool runner
(e.g. ``run shfmt``) to stamp files with provenance.  Format fields:
``command`` (full command path) and ``version`` (package version).
"""


def generated_header(command: str, comment_prefix: str = "# ") -> str:
    """Return a generated-by header block with timestamp.

    :param command: Full command path (e.g. ``repomatic sync-mailmap``).
    :param comment_prefix: Comment prefix for the target format.
    """
    from datetime import datetime, timezone

    from . import __version__

    line1 = GENERATED_HEADER_TEMPLATE.format(command=command, version=__version__)
    line2 = f"Timestamp: {datetime.now(tz=timezone.utc).isoformat()}"
    return f"{comment_prefix}{line1}\n{comment_prefix}{line2}\n"


class ArchiveFormat(Enum):
    """Archive format for binary tool downloads."""

    RAW = "raw"
    TAR_GZ = "tar.gz"
    TAR_XZ = "tar.xz"
    ZIP = "zip"

    def tarfile_mode(self) -> Literal["r:gz", "r:xz"]:
        """Return the ``tarfile.open`` mode string for this format.

        :raises ValueError: If called on a non-tar format.
        """
        if self is ArchiveFormat.TAR_GZ:
            return "r:gz"
        if self is ArchiveFormat.TAR_XZ:
            return "r:xz"
        msg = f"{self.value} is not a tar archive"
        raise ValueError(msg)


class NativeFormat(Enum):
    """Target format for ``[tool.X]`` translation."""

    YAML = "yaml"
    TOML = "toml"
    JSON = "json"
    EDITORCONFIG = "editorconfig"

    def _header(self, tool_name: str) -> str:
        """Return a generated-by header block in this format's comment syntax.

        JSON has no standard comment syntax, so returns an empty string.
        """
        if self is NativeFormat.JSON:
            return ""
        # YAML, TOML, and editorconfig all use ``#`` comments.
        return generated_header(f"repomatic run {tool_name}")

    def serialize(self, data: dict, tool_name: str = "") -> str:
        """Serialize a config dict to this format's string representation.

        :param data: Configuration dictionary to serialize.
        :param tool_name: Tool name for the generated-by header comment.
        """
        header = self._header(tool_name) if tool_name else ""
        if self is NativeFormat.YAML:
            return header + yaml.safe_dump(
                data, default_flow_style=False, sort_keys=False
            )
        if self is NativeFormat.TOML:
            return header + tomlkit.dumps(data)
        if self is NativeFormat.EDITORCONFIG:
            return self._serialize_editorconfig(data, header)
        return json.dumps(data, indent=2) + "\n"

    @staticmethod
    def _serialize_editorconfig(data: dict, header: str) -> str:
        """Serialize a flat dict to editorconfig format.

        Emits all keys under ``[*]`` (match-all glob). TOML-style hyphens in
        key names are converted to underscores (editorconfig convention).
        """
        lines = [f"{header}root = true", "", "[*]"]
        for key, value in data.items():
            ec_key = key.replace("-", "_")
            if isinstance(value, bool):
                lines.append(f"{ec_key} = {str(value).lower()}")
            else:
                lines.append(f"{ec_key} = {value}")
        return "\n".join(lines) + "\n"


PlatformKey = tuple[Platform | Group, Architecture]
"""A ``(platform_or_group, architecture)`` pair used as binary lookup key.

The platform element can be a single :class:`~extra_platforms.Platform` (like
``MACOS``) or a :class:`~extra_platforms.Group` (like ``LINUX``, which matches
any Linux distribution). The architecture is always a concrete
:class:`~extra_platforms.Architecture`.

Resolution order in :meth:`BinarySpec.resolve_platform`:

1. Exact Platform match (``current_platform() == key_platform``).
2. Group membership (``current_platform() in key_group``), preferring the
   group with fewest members (most specific).
"""


@dataclass(frozen=True)
class BinarySpec:
    """Platform-specific binary download specification.

    Keys are :data:`PlatformKey` tuples pairing an extra-platforms
    :class:`~extra_platforms.Platform` or :class:`~extra_platforms.Group`
    with an :class:`~extra_platforms.Architecture`. This lets callers use
    broad groups (``LINUX`` matches any distro) or specific platforms
    (``DEBIAN``) with full detection heuristics from extra-platforms.

    .. hint::
        Structural integrity checks (key types, checksum format, URL
        placeholders, strip_components consistency) are enforced in
        ``test_tool_spec_integrity``. If the registry becomes
        user-configurable in the future, move these checks to
        ``__post_init__``.
    """

    urls: dict[PlatformKey, str]
    """Platform key to URL template mapping. URLs use ``{version}`` placeholders."""

    checksums: dict[PlatformKey, str]
    """Platform key to SHA-256 hex digest mapping."""

    archive_format: ArchiveFormat | dict[PlatformKey | Platform | Group, ArchiveFormat]
    """Archive format of the downloaded file.

    A single :class:`ArchiveFormat` applies to every platform. A dict maps
    platform specifiers to formats, allowing mixed archives in one spec::

        archive_format={ALL_PLATFORMS: ArchiveFormat.TAR_GZ, WINDOWS: ArchiveFormat.ZIP}

    Dict keys follow the same resolution as :meth:`resolve_platform`:
    exact :data:`PlatformKey` tuple first, then bare
    :class:`~extra_platforms.Platform` equality, then
    :class:`~extra_platforms.Group` membership (smallest group wins).
    """

    archive_executable: str | None = None
    """Path of the executable inside the archive. ``None`` defaults to the
    tool name. For ``RAW`` format, used as the final filename.
    """

    strip_components: int = 0
    """Number of leading path components to strip when extracting."""

    def resolve_platform(self) -> PlatformKey:
        """Match the current environment against registered platform keys.

        Uses ``current_platform()`` and ``current_architecture()`` from
        extra-platforms, inheriting its full detection heuristics.

        :return: The matching :data:`PlatformKey`.
        :raises RuntimeError: If no key matches the current environment.
        """
        arch = current_architecture()
        plat = current_platform()

        # Pass 1: exact Platform match (highest priority).
        for key_plat, key_arch in self.urls:
            if key_arch == arch and isinstance(key_plat, Platform) and key_plat == plat:
                return (key_plat, key_arch)

        # Pass 2: Group membership (prefer smallest group = most specific).
        candidates: list[tuple[Group, Architecture]] = []
        for key_plat, key_arch in self.urls:
            if key_arch == arch and isinstance(key_plat, Group) and plat in key_plat:
                candidates.append((key_plat, key_arch))

        if len(candidates) == 1:
            return candidates[0]
        if candidates:
            # Most-specific group: fewest members.
            return min(candidates, key=lambda c: len(c[0]))

        available = ", ".join(
            f"{k[0].name} {k[1].name}" for k in sorted(self.urls, key=str)
        )
        msg = f"No binary for {plat.name} {arch.name}. Available: {available}."
        raise RuntimeError(msg)

    def get_archive_format(self, key: PlatformKey) -> ArchiveFormat:
        """Return the archive format for the given platform key.

        When ``archive_format`` is a single :class:`ArchiveFormat`, returns
        it directly. When it is a dict, resolves in order: exact
        :data:`PlatformKey` tuple, bare Platform equality, then Group
        membership (smallest group wins).
        """
        if isinstance(self.archive_format, ArchiveFormat):
            return self.archive_format

        fmt_map = self.archive_format

        # Exact tuple match.
        if key in fmt_map:
            return fmt_map[key]

        # Bare Platform or Group match.
        key_plat = key[0]
        group_hits: list[tuple[Group, ArchiveFormat]] = []
        for map_key, fmt in fmt_map.items():
            if isinstance(map_key, tuple):
                continue
            if map_key == key_plat:
                return fmt
            if isinstance(map_key, Group) and (
                isinstance(key_plat, Platform)
                and key_plat in map_key
                or isinstance(key_plat, Group)
                and (key_plat & map_key)
            ):
                group_hits.append((map_key, fmt))

        if group_hits:
            # Most-specific group: fewest members.
            return min(group_hits, key=lambda h: len(h[0]))[1]

        msg = f"No archive format for {key[0].name} {key[1].name}"
        raise ValueError(msg)

    @staticmethod
    def platform_cache_key(key: PlatformKey) -> str:
        """Derive a filesystem-safe cache path segment from a platform key.

        :return: A string like ``linux-aarch64`` or ``macos-x86_64``.
        """
        return f"{key[0].id}-{key[1].id}"


@dataclass(frozen=True)
class ToolSpec:
    """Specification for an external tool managed by repomatic.

    .. hint::
        Structural integrity checks (name format, version format, flag
        conventions, field consistency) are enforced in
        ``test_tool_spec_integrity``. If the registry becomes user-configurable
        in the future, move these checks to ``__post_init__``.

    .. hint:: CLI parser quirks for ``config_after_subcommand``

        Tools that use subcommands (``tool <subcmd> [flags] [files]``) may
        require ``config_flag`` to appear after the subcommand name, depending
        on the CLI parser framework:

        - **clap** (Rust): global flags accepted before or after the
          subcommand. No special handling needed. Used by: ruff, labelmaker.
        - **cobra** (Go): root-level flags inherited by all subcommands,
          accepted in both positions. No special handling needed.
          Used by: gitleaks.
        - **click** (Python): global flags accepted before or after the
          subcommand. No special handling needed. Used by: bump-my-version.
        - **bpaf** (Rust): ``#[bpaf(external)]`` fields are scoped inside
          the subcommand variant, so ``tool <subcmd> --flag`` works but
          ``tool --flag <subcmd>`` does not. Set
          ``config_after_subcommand=True``. Used by: biome.
    """

    name: str
    """Tool identity: CLI name for ``repomatic run <name>``, default PyPI
    package name, and default executable name.
    """

    display_name: str | None = None
    """Human-readable name with proper casing for documentation (like
    ``'Biome'``, ``'Gitleaks'``). ``None`` defaults to ``name``.
    """

    version: str = ""
    """Pinned version (e.g., ``'1.38.0'``)."""

    package: str | None = None
    """PyPI package name. ``None`` defaults to ``name``. Only set when the
    package name differs from the tool name.
    """

    executable: str | None = None
    """Executable name if different from the tool name. ``None`` defaults to
    the registry key.
    """

    native_config_files: tuple[str, ...] = ()
    """Config filenames the tool auto-discovers, checked in order.

    Paths relative to repo root (e.g., ``'zizmor.yaml'``,
    ``'.github/actionlint.yaml'``). Empty for tools with no config file.
    """

    config_flag: str | None = None
    """CLI flag to pass a config file path (e.g., ``'--config'``,
    ``'--config-file'``). ``None`` if the tool only reads from fixed paths.
    """

    native_format: NativeFormat = NativeFormat.YAML
    """Target format for ``[tool.X]`` translation."""

    default_config: str | None = None
    """Filename in ``repomatic/data/`` for bundled defaults, stored in
    ``native_format``. ``None`` if no bundled default exists.
    """

    reads_pyproject: bool = False
    """Whether the tool natively reads ``[tool.X]`` from ``pyproject.toml``.

    When ``True`` and ``[tool.X]`` exists in ``pyproject.toml``, repomatic
    skips Level 2 translation (the tool reads it directly). Resolution still
    falls through to Level 3 (bundled default) and Level 4 (bare) when no
    config is found.
    """

    default_flags: tuple[str, ...] = ()
    """Flags always passed to the tool (e.g., ``('--strict',)``)."""

    ci_flags: tuple[str, ...] = ()
    """Flags added only when ``$GITHUB_ACTIONS`` is set (e.g., output format)."""

    with_packages: tuple[str, ...] = ()
    """Extra packages installed alongside the tool (e.g., mdformat plugins).

    Passed as ``--with <pkg>`` to uvx.
    """

    needs_venv: bool = False
    """If ``True``, use ``uv run`` (project venv) instead of ``uvx`` (isolated).

    Required when the tool imports project code (mypy, pytest).
    """

    computed_params: Callable[[Metadata], list[str]] | None = None
    """Callable that receives a ``Metadata`` instance and returns extra CLI args
    derived from project metadata (e.g., mypy's ``--python-version`` from
    ``requires-python``). ``None`` if no computed params.
    """

    config_after_subcommand: bool = False
    """Insert ``config_flag`` after the first token of ``extra_args``.

    Needed for tools whose CLI parser (e.g., bpaf) scopes global options inside
    the subcommand, so ``tool subcommand --config-path X`` is valid but
    ``tool --config-path X subcommand`` is not. When ``True``, ``config_args``
    are spliced after the first element of ``extra_args`` (the subcommand name).
    """

    post_process: Callable[[Sequence[str]], None] | None = None
    """Callback invoked on ``extra_args`` after the tool exits successfully.

    Intended for temporary workarounds that fix known upstream formatting bugs
    in-place. Remove the callback once upstream ships the fix.
    """

    binary: BinarySpec | None = None
    """Platform-specific binary download spec. When set, the tool is downloaded
    as a binary instead of installed via ``uvx`` or ``uv run``.
    """

    source_url: str | None = None
    """GitHub repository or project homepage URL."""

    config_docs_url: str | None = None
    """URL to the tool's configuration reference."""

    cli_docs_url: str | None = None
    """URL to the tool's CLI usage documentation."""


# ---------------------------------------------------------------------------
# Post-process callbacks
# ---------------------------------------------------------------------------

_DIRECTIVE_YAML_OPTIONS_RE = re.compile(
    r"^((?:`{3,}|:{3,})\{[^}]+\}[^\n]*\n)"
    r"---\n"
    r"((?:[^\n]+\n)+?)"
    r"---\n",
    re.MULTILINE,
)
"""Match YAML-block directive options immediately after a MyST fence opening.

.. note::
    Workaround for `executablebooks/mdformat-myst#21
    <https://github.com/executablebooks/mdformat-myst/issues/21>`_ where
    ``mdformat-myst`` unconditionally converts ``:key: value`` directive
    options to YAML blocks (``---`` / ``key: value`` / ``---``). Remove when
    upstream merges `executablebooks/mdformat-myst#49
    <https://github.com/executablebooks/mdformat-myst/pull/49>`_.
"""


def _yaml_block_to_field_list(match: re.Match[str]) -> str:
    """Convert a single YAML-block directive option to field-list syntax."""
    directive_line = match.group(1)
    yaml_lines = match.group(2)
    # Prepend ":" to each non-empty line: ``key: value`` → ``:key: value``.
    field_lines = re.sub(r"^(?=\S)", ":", yaml_lines, flags=re.MULTILINE)
    return directive_line + field_lines


def _fix_myst_directive_options(extra_args: Sequence[str]) -> None:
    """Rewrite YAML-block directive options back to field-list syntax.

    Operates in-place on every file in *extra_args* that exists on disk.
    Files without matching patterns are left untouched.
    """
    for arg in extra_args:
        path = Path(arg)
        if not path.is_file():
            continue
        content = path.read_text(encoding="utf-8")
        fixed = _DIRECTIVE_YAML_OPTIONS_RE.sub(_yaml_block_to_field_list, content)
        if fixed != content:
            path.write_text(fixed, encoding="utf-8")
            logging.debug("Fixed MyST directive options in %s", path)


# ---------------------------------------------------------------------------
# Tool registry
# ---------------------------------------------------------------------------

TOOL_REGISTRY: dict[str, ToolSpec] = {
    "actionlint": ToolSpec(
        name="actionlint",
        version="1.7.12",
        native_config_files=(".github/actionlint.yaml",),
        native_format=NativeFormat.YAML,
        default_flags=("-color",),
        source_url="https://github.com/rhysd/actionlint",
        config_docs_url="https://github.com/rhysd/actionlint/blob/main/docs/config.md",
        cli_docs_url="https://github.com/rhysd/actionlint/blob/main/docs/usage.md",
        binary=BinarySpec(
            urls={
                (
                    LINUX,
                    AARCH64,
                ): "https://github.com/rhysd/actionlint/releases/download/v{version}/actionlint_{version}_linux_arm64.tar.gz",
                (
                    LINUX,
                    X86_64,
                ): "https://github.com/rhysd/actionlint/releases/download/v{version}/actionlint_{version}_linux_amd64.tar.gz",
                (
                    MACOS,
                    AARCH64,
                ): "https://github.com/rhysd/actionlint/releases/download/v{version}/actionlint_{version}_darwin_arm64.tar.gz",
                (
                    MACOS,
                    X86_64,
                ): "https://github.com/rhysd/actionlint/releases/download/v{version}/actionlint_{version}_darwin_amd64.tar.gz",
                (
                    WINDOWS,
                    AARCH64,
                ): "https://github.com/rhysd/actionlint/releases/download/v{version}/actionlint_{version}_windows_arm64.zip",
                (
                    WINDOWS,
                    X86_64,
                ): "https://github.com/rhysd/actionlint/releases/download/v{version}/actionlint_{version}_windows_amd64.zip",
            },
            checksums={
                (
                    LINUX,
                    AARCH64,
                ): "325e971b6ba9bfa504672e29be93c24981eeb1c07576d730e9f7c8805afff0c6",
                (
                    LINUX,
                    X86_64,
                ): "8aca8db96f1b94770f1b0d72b6dddcb1ebb8123cb3712530b08cc387b349a3d8",
                (
                    MACOS,
                    AARCH64,
                ): "aba9ced2dee8d27fecca3dc7feb1a7f9a52caefa1eb46f3271ea66b6e0e6953f",
                (
                    MACOS,
                    X86_64,
                ): "5b44c3bc2255115c9b69e30efc0fecdf498fdb63c5d58e17084fd5f16324c644",
                (
                    WINDOWS,
                    AARCH64,
                ): "cadcf7ea4efe3a68728893813643cebe1185e5b1d4be5b96245f65c9a4d5ea41",
                (
                    WINDOWS,
                    X86_64,
                ): "6e7241b51e6817ea6a047693d8e6fed13b31819c9a0dd6c5a726e1592d22f6e9",
            },
            archive_format={
                ALL_PLATFORMS: ArchiveFormat.TAR_GZ,
                WINDOWS: ArchiveFormat.ZIP,
            },
        ),
    ),
    "autopep8": ToolSpec(
        name="autopep8",
        version="2.3.2",
        source_url="https://github.com/hhatto/autopep8",
        cli_docs_url="https://pypi.org/project/autopep8/",
        default_flags=(
            "--recursive",
            "--in-place",
            "--max-line-length",
            "88",
            "--select",
            "E501",
        ),
    ),
    "biome": ToolSpec(
        name="biome",
        display_name="Biome",
        version="2.4.5",
        source_url="https://github.com/biomejs/biome",
        config_docs_url="https://biomejs.dev/reference/configuration/",
        cli_docs_url="https://biomejs.dev/reference/cli/",
        native_config_files=("biome.json", "biome.jsonc"),
        config_flag="--config-path",
        config_after_subcommand=True,
        native_format=NativeFormat.JSON,
        binary=BinarySpec(
            urls={
                (
                    LINUX,
                    AARCH64,
                ): "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%40{version}/biome-linux-arm64",
                (
                    LINUX,
                    X86_64,
                ): "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%40{version}/biome-linux-x64",
                (
                    MACOS,
                    AARCH64,
                ): "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%40{version}/biome-darwin-arm64",
                (
                    MACOS,
                    X86_64,
                ): "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%40{version}/biome-darwin-x64",
                (
                    WINDOWS,
                    AARCH64,
                ): "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%40{version}/biome-win32-arm64.exe",
                (
                    WINDOWS,
                    X86_64,
                ): "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%40{version}/biome-win32-x64.exe",
            },
            checksums={
                (
                    LINUX,
                    AARCH64,
                ): "98a109d54bfea7df1e82b73aa7d37fc2caa880d12105eb2495efe0d653955518",
                (
                    LINUX,
                    X86_64,
                ): "a31815f19b0b90fa043eb23fbf769ed931fbcde6d98bb89894ea8be1387d8394",
                (
                    MACOS,
                    AARCH64,
                ): "b50a1a5adca140554f44f6c89edcf6383b0b2e3baf9dcd08d597d1fd59f92544",
                (
                    MACOS,
                    X86_64,
                ): "7f4d800ddc37c84a0a09aac1cd1ec77d1bbbdd5f97727f36f2062f6b639714e9",
                (
                    WINDOWS,
                    AARCH64,
                ): "12750283a136a1535bcd87e76c67d855d6452274144464afe1c4e7184c1931c3",
                (
                    WINDOWS,
                    X86_64,
                ): "8d382e6a5cd88f381eb7c2825bcce4fec0660fe366e93f95c8e6e2415fe16d21",
            },
            archive_format=ArchiveFormat.RAW,
        ),
    ),
    "bump-my-version": ToolSpec(
        name="bump-my-version",
        version="1.2.7",
        reads_pyproject=True,
        source_url="https://github.com/callowayproject/bump-my-version",
        config_docs_url="https://callowayproject.github.io/bump-my-version/reference/configuration/",
        cli_docs_url="https://callowayproject.github.io/bump-my-version/reference/cli/",
    ),
    "gitleaks": ToolSpec(
        name="gitleaks",
        display_name="Gitleaks",
        version="8.30.1",
        source_url="https://github.com/gitleaks/gitleaks",
        config_docs_url="https://github.com/gitleaks/gitleaks#configuration",
        cli_docs_url="https://github.com/gitleaks/gitleaks#usage",
        native_config_files=(".gitleaks.toml", ".github/gitleaks.toml"),
        config_flag="--config",
        native_format=NativeFormat.TOML,
        binary=BinarySpec(
            urls={
                (
                    LINUX,
                    AARCH64,
                ): "https://github.com/gitleaks/gitleaks/releases/download/v{version}/gitleaks_{version}_linux_arm64.tar.gz",
                (
                    LINUX,
                    X86_64,
                ): "https://github.com/gitleaks/gitleaks/releases/download/v{version}/gitleaks_{version}_linux_x64.tar.gz",
                (
                    MACOS,
                    AARCH64,
                ): "https://github.com/gitleaks/gitleaks/releases/download/v{version}/gitleaks_{version}_darwin_arm64.tar.gz",
                (
                    MACOS,
                    X86_64,
                ): "https://github.com/gitleaks/gitleaks/releases/download/v{version}/gitleaks_{version}_darwin_x64.tar.gz",
                (
                    WINDOWS,
                    AARCH64,
                ): "https://github.com/gitleaks/gitleaks/releases/download/v{version}/gitleaks_{version}_windows_arm64.zip",
                (
                    WINDOWS,
                    X86_64,
                ): "https://github.com/gitleaks/gitleaks/releases/download/v{version}/gitleaks_{version}_windows_x64.zip",
            },
            checksums={
                (
                    LINUX,
                    AARCH64,
                ): "e4a487ee7ccd7d3a7f7ec08657610aa3606637dab924210b3aee62570fb4b080",
                (
                    LINUX,
                    X86_64,
                ): "551f6fc83ea457d62a0d98237cbad105af8d557003051f41f3e7ca7b3f2470eb",
                (
                    MACOS,
                    AARCH64,
                ): "b40ab0ae55c505963e365f271a8d3846efbc170aa17f2607f13df610a9aeb6a5",
                (
                    MACOS,
                    X86_64,
                ): "dfe101a4db2255fc85120ac7f3d25e4342c3c20cf749f2c20a18081af1952709",
                (
                    WINDOWS,
                    AARCH64,
                ): "b95f5e4f5c425cedca7ee203d9afd29597e692c4924a12ed42f970537c72cc0f",
                (
                    WINDOWS,
                    X86_64,
                ): "d29144deff3a68aa93ced33dddf84b7fdc26070add4aa0f4513094c8332afc4e",
            },
            archive_format={
                ALL_PLATFORMS: ArchiveFormat.TAR_GZ,
                WINDOWS: ArchiveFormat.ZIP,
            },
        ),
    ),
    "labelmaker": ToolSpec(
        name="labelmaker",
        version="0.6.4",
        source_url="https://github.com/jwodder/labelmaker",
        cli_docs_url="https://github.com/jwodder/labelmaker",
        binary=BinarySpec(
            urls={
                (
                    LINUX,
                    AARCH64,
                ): "https://github.com/jwodder/labelmaker/releases/download/v{version}/labelmaker-aarch64-unknown-linux-gnu.tar.xz",
                (
                    LINUX,
                    X86_64,
                ): "https://github.com/jwodder/labelmaker/releases/download/v{version}/labelmaker-x86_64-unknown-linux-gnu.tar.xz",
                (
                    MACOS,
                    AARCH64,
                ): "https://github.com/jwodder/labelmaker/releases/download/v{version}/labelmaker-aarch64-apple-darwin.tar.xz",
                (
                    MACOS,
                    X86_64,
                ): "https://github.com/jwodder/labelmaker/releases/download/v{version}/labelmaker-x86_64-apple-darwin.tar.xz",
                (
                    WINDOWS,
                    X86_64,
                ): "https://github.com/jwodder/labelmaker/releases/download/v{version}/labelmaker-x86_64-pc-windows-msvc.zip",
            },
            checksums={
                (
                    LINUX,
                    AARCH64,
                ): "4685e142da55150904d16624fe1052161de5dba1a859cddef19ab41833c37728",
                (
                    LINUX,
                    X86_64,
                ): "d76f8e64f9671884dac1758fe54a28a6680c5d9bf0ffd593a2c68ba558cc49a2",
                (
                    MACOS,
                    AARCH64,
                ): "a52a4e102f0760ce1632da5fdaee2b0debe0e6ddea577b88a94a60172fe85751",
                (
                    MACOS,
                    X86_64,
                ): "dc8374d6a9bec4ebf143fb42e3024aeffabe8585bb9bd6f134cfaf0693be7688",
                (
                    WINDOWS,
                    X86_64,
                ): "939195930f9d5fd2b15a5cf43497019a52083e6c6713807d3379de49395c2e10",
            },
            archive_format={
                ALL_PLATFORMS: ArchiveFormat.TAR_XZ,
                WINDOWS: ArchiveFormat.ZIP,
            },
            strip_components=1,
        ),
    ),
    "lychee": ToolSpec(
        name="lychee",
        display_name="Lychee",
        version="0.23.0",
        source_url="https://github.com/lycheeverse/lychee",
        config_docs_url="https://lychee.cli.rs/configuration/",
        cli_docs_url="https://lychee.cli.rs/usage/cli/",
        native_config_files=("lychee.toml",),
        config_flag="--config",
        native_format=NativeFormat.TOML,
        binary=BinarySpec(
            urls={
                (
                    LINUX,
                    AARCH64,
                ): "https://github.com/lycheeverse/lychee/releases/download/lychee-v{version}/lychee-aarch64-unknown-linux-gnu.tar.gz",
                (
                    LINUX,
                    X86_64,
                ): "https://github.com/lycheeverse/lychee/releases/download/lychee-v{version}/lychee-x86_64-unknown-linux-gnu.tar.gz",
                (
                    MACOS,
                    AARCH64,
                ): "https://github.com/lycheeverse/lychee/releases/download/lychee-v{version}/lychee-arm64-macos.tar.gz",
                (
                    WINDOWS,
                    X86_64,
                ): "https://github.com/lycheeverse/lychee/releases/download/lychee-v{version}/lychee-x86_64-windows.exe",
            },
            checksums={
                (
                    LINUX,
                    AARCH64,
                ): "97eb93b02a7d78a752fc33e5b0983439ccaadbf3db952b68a0a4401acd92e6e0",
                (
                    LINUX,
                    X86_64,
                ): "1fcb6ccf10d04c22b8c5873c5b9cb7be32ee7423e12169d6f1a79a6f1962ef81",
                (
                    MACOS,
                    AARCH64,
                ): "1953bb425486e1b887757201e54e8fdf866c9cada6c270d8f6ed21ffbed4145a",
                (
                    WINDOWS,
                    X86_64,
                ): "0fda7ff0a60c0250939fc25361c2d4e6e7853c31c996733fdd5a1dd760bcb824",
            },
            archive_format={
                ALL_PLATFORMS: ArchiveFormat.TAR_GZ,
                WINDOWS: ArchiveFormat.RAW,
            },
        ),
    ),
    # TODO: add config_flag="--config" once upstream adds --config support.
    #   See https://github.com/hukkin/mdformat/issues/432
    #   and https://github.com/hukkin/mdformat/issues/562
    "mdformat": ToolSpec(
        name="mdformat",
        version="1.0.0",
        source_url="https://github.com/hukkin/mdformat",
        config_docs_url="https://mdformat.readthedocs.io/en/stable/users/configuration_file.html",
        cli_docs_url="https://mdformat.readthedocs.io/en/stable/users/cli.html",
        native_config_files=(".mdformat.toml",),
        native_format=NativeFormat.TOML,
        default_config="mdformat.toml",
        reads_pyproject=True,
        default_flags=("--strict-front-matter",),
        with_packages=(
            "mdformat_admon==2.1.1",
            "mdformat-config==0.2.1",
            "mdformat_deflist==0.1.4",
            "mdformat_footnote==0.1.3",
            "mdformat-front-matters==2.0.0",
            "mdformat-gfm==1.0.0",
            "mdformat_gfm_alerts==2.0.0",
            "mdformat_myst==0.3.0",
            "mdformat-pelican @ git+https://github.com/kdeldycke/mdformat-pelican@fix-mdformat-1.0.0",
            "mdformat_pyproject==0.1.1",
            "mdformat-recover-urls==0.0.2",
            "mdformat-ruff==0.1.3",
            "mdformat-shfmt==0.2.0",
            "mdformat_simple_breaks==0.1.0",
            "mdformat-toc==0.5.0",
            "mdformat-web==0.2.0",
            "ruff==0.15.5",
        ),
        post_process=_fix_myst_directive_options,
    ),
    "mypy": ToolSpec(
        name="mypy",
        version="1.19.1",
        source_url="https://github.com/python/mypy",
        config_docs_url="https://mypy.readthedocs.io/en/stable/config_file.html",
        cli_docs_url="https://mypy.readthedocs.io/en/stable/command_line.html",
        reads_pyproject=True,
        needs_venv=True,
        default_flags=("--color-output",),
        computed_params=lambda m: m.mypy_params or [],
    ),
    "pyproject-fmt": ToolSpec(
        name="pyproject-fmt",
        version="2.16.2",
        source_url="https://github.com/tox-dev/pyproject-fmt",
        config_docs_url="https://pyproject-fmt.readthedocs.io/en/latest/",
        cli_docs_url="https://pyproject-fmt.readthedocs.io/en/latest/",
        reads_pyproject=True,
        default_flags=(
            "--expand-tables",
            "project.entry-points,project.optional-dependencies,project.urls,project.scripts",
        ),
    ),
    "ruff": ToolSpec(
        name="ruff",
        display_name="Ruff",
        version="0.15.5",
        source_url="https://github.com/astral-sh/ruff",
        config_docs_url="https://docs.astral.sh/ruff/configuration/",
        cli_docs_url="https://docs.astral.sh/ruff/configuration/#command-line-interface",
        native_config_files=("ruff.toml", ".ruff.toml"),
        config_flag="--config",
        native_format=NativeFormat.TOML,
        default_config="ruff.toml",
        reads_pyproject=True,
    ),
    "shfmt": ToolSpec(
        name="shfmt",
        version="3.13.1",
        source_url="https://github.com/mvdan/sh",
        config_docs_url="https://github.com/mvdan/sh#editorconfig",
        cli_docs_url="https://github.com/mvdan/sh#usage",
        native_config_files=(".editorconfig",),
        native_format=NativeFormat.EDITORCONFIG,
        default_flags=("--write",),
        binary=BinarySpec(
            urls={
                (
                    LINUX,
                    AARCH64,
                ): "https://github.com/mvdan/sh/releases/download/v{version}/shfmt_v{version}_linux_arm64",
                (
                    LINUX,
                    X86_64,
                ): "https://github.com/mvdan/sh/releases/download/v{version}/shfmt_v{version}_linux_amd64",
                (
                    MACOS,
                    AARCH64,
                ): "https://github.com/mvdan/sh/releases/download/v{version}/shfmt_v{version}_darwin_arm64",
                (
                    MACOS,
                    X86_64,
                ): "https://github.com/mvdan/sh/releases/download/v{version}/shfmt_v{version}_darwin_amd64",
                (
                    WINDOWS,
                    X86_64,
                ): "https://github.com/mvdan/sh/releases/download/v{version}/shfmt_v{version}_windows_amd64.exe",
            },
            checksums={
                (
                    LINUX,
                    AARCH64,
                ): "32d92acaa5cd8abb29fc49dac123dc412442d5713967819d8af2c29f1b3857c7",
                (
                    LINUX,
                    X86_64,
                ): "fb096c5d1ac6beabbdbaa2874d025badb03ee07929f0c9ff67563ce8c75398b1",
                (
                    MACOS,
                    AARCH64,
                ): "9680526be4a66ea1ffe988ed08af58e1400fe1e4f4aef5bd88b20bb9b3da33f8",
                (
                    MACOS,
                    X86_64,
                ): "6feedafc72915794163114f512348e2437d080d0047ef8b8fa2ec63b575f12af",
                (
                    WINDOWS,
                    X86_64,
                ): "60cd368533d0ad73fa86d93d5bbf95ef40587245ce684ed138c1b31557b5fe97",
            },
            archive_format=ArchiveFormat.RAW,
        ),
    ),
    "typos": ToolSpec(
        name="typos",
        version="1.44.0",
        source_url="https://github.com/crate-ci/typos",
        config_docs_url="https://github.com/crate-ci/typos/blob/master/docs/reference.md",
        cli_docs_url="https://github.com/crate-ci/typos/blob/master/docs/reference.md",
        reads_pyproject=True,
        default_flags=("--write-changes",),
        binary=BinarySpec(
            urls={
                (
                    LINUX,
                    AARCH64,
                ): "https://github.com/crate-ci/typos/releases/download/v{version}/typos-v{version}-aarch64-unknown-linux-musl.tar.gz",
                (
                    LINUX,
                    X86_64,
                ): "https://github.com/crate-ci/typos/releases/download/v{version}/typos-v{version}-x86_64-unknown-linux-musl.tar.gz",
                (
                    MACOS,
                    AARCH64,
                ): "https://github.com/crate-ci/typos/releases/download/v{version}/typos-v{version}-aarch64-apple-darwin.tar.gz",
                (
                    MACOS,
                    X86_64,
                ): "https://github.com/crate-ci/typos/releases/download/v{version}/typos-v{version}-x86_64-apple-darwin.tar.gz",
                (
                    WINDOWS,
                    X86_64,
                ): "https://github.com/crate-ci/typos/releases/download/v{version}/typos-v{version}-x86_64-pc-windows-msvc.zip",
            },
            checksums={
                (
                    LINUX,
                    AARCH64,
                ): "132c20fc5e3c9ba540ec55a0a468dcb9c1504625a405df1c237b10dd4f2ec433",
                (
                    LINUX,
                    X86_64,
                ): "1b788b7d764e2f20fe089487428a3944ed218d1fb6fcd8eac4230b5893a38779",
                (
                    MACOS,
                    AARCH64,
                ): "ca82d593351dbac519a5c9fa832fc147b176d80100d00d08e855fcb46d43882d",
                (
                    MACOS,
                    X86_64,
                ): "70e7cbfd9c0bac3b27d096171413a8fff989cc9f9227d3ef66694ed99fdc7b5c",
                (
                    WINDOWS,
                    X86_64,
                ): "afd85c8f3c5c925ee7452389acdf70b048d8c6eae5e52a581e63a7d1b7655f17",
            },
            archive_format={
                ALL_PLATFORMS: ArchiveFormat.TAR_GZ,
                WINDOWS: ArchiveFormat.ZIP,
            },
        ),
    ),
    "yamllint": ToolSpec(
        name="yamllint",
        version="1.38.0",
        source_url="https://github.com/adrienverge/yamllint",
        config_docs_url="https://yamllint.readthedocs.io/en/stable/configuration.html",
        cli_docs_url="https://yamllint.readthedocs.io/en/stable/quickstart.html",
        native_config_files=(
            ".yamllint.yaml",
            ".yamllint.yml",
            ".yamllint",
        ),
        config_flag="--config-file",
        default_config="yamllint.yaml",
        default_flags=("--strict",),
        ci_flags=("--format", "github"),
    ),
    "zizmor": ToolSpec(
        name="zizmor",
        version="1.23.0",
        source_url="https://github.com/zizmorcore/zizmor",
        config_docs_url="https://docs.zizmor.sh/configuration/",
        cli_docs_url="https://docs.zizmor.sh/usage/",
        native_config_files=("zizmor.yaml",),
        config_flag="--config",
        default_config="zizmor.yaml",
        default_flags=("--offline",),
        ci_flags=("--format", "github"),
    ),
}


# ---------------------------------------------------------------------------
# Bundled data file access
# ---------------------------------------------------------------------------


@contextmanager
def get_data_file_path(filename: str) -> Iterator[Path]:
    """Yield the filesystem path of a bundled data file.

    Unlike ``init_project.get_data_content()`` which returns string content,
    this yields a ``Path`` suitable for passing to external tools via
    ``--config <path>``. The path is valid only within the context manager.
    """
    data_files = files("repomatic.data")
    with as_file(data_files.joinpath(filename)) as path:
        if not path.exists():
            msg = f"Bundled data file not found: {filename}"
            raise FileNotFoundError(msg)
        yield path


# ---------------------------------------------------------------------------
# Config resolution
# ---------------------------------------------------------------------------


def load_pyproject_tool_section(tool_name: str) -> dict[str, Any]:
    """Load ``[tool.<tool_name>]`` from ``pyproject.toml`` in the current directory.

    :return: The tool's config dict, or empty dict if not found.
    """
    pyproject_path = Path("pyproject.toml")
    if not pyproject_path.exists():
        logging.debug("No pyproject.toml found in CWD.")
        return {}
    pyproject_data = tomllib.loads(pyproject_path.read_text(encoding="UTF-8"))
    tool_section: dict[str, Any] = pyproject_data.get("tool", {}).get(tool_name, {})
    if tool_section:
        logging.debug("[tool.%s] found in pyproject.toml: %r", tool_name, tool_section)
    else:
        logging.debug("No [tool.%s] section in pyproject.toml.", tool_name)
    return tool_section


def _config_filename(spec: ToolSpec) -> str:
    """Derive the canonical config filename for the cache.

    Uses the first ``native_config_files`` entry (without leading dots or path
    components) if available, otherwise constructs from the native format
    extension.
    """
    if spec.native_config_files:
        return Path(spec.native_config_files[0]).name.lstrip(".")
    return f"{spec.name}.{spec.native_format.value}"


def _store_config_to_cache(
    spec: ToolSpec,
    content: str,
) -> tuple[list[str], Path | None]:
    """Write config content to the cache and return CLI args.

    :return: ``([flag, cache_path], None)`` on success, or falls back to a temp
        file returning ``([flag, tmp_path], tmp_path)`` if the cache is not
        writable.
    """
    from .cache import store_config

    assert spec.config_flag is not None
    filename = _config_filename(spec)
    cached = store_config(spec.name, filename, content)
    if cached is not None:
        logging.info(
            "%s: config cached at %s, passing via %s.",
            spec.name,
            cached,
            spec.config_flag,
        )
        return [spec.config_flag, str(cached)], None

    # Cache not writable — fall back to temp file.
    logging.warning(
        "%s: cache directory not writable, falling back to temp file.",
        spec.name,
    )
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=f".{spec.native_format.value}",
        prefix=f"repomatic-{spec.name}-",
        delete=False,
    ) as tmp:
        tmp.write(content)
    tmp_path = Path(tmp.name)
    return [spec.config_flag, str(tmp_path)], tmp_path


def _write_cwd_config(spec: ToolSpec, content: str, level: int) -> Path:
    """Write config content to the first native config path for CWD-discovery.

    For tools without a ``--config`` flag. The caller must clean up the file
    after the tool exits.

    :param spec: Tool specification (must have ``native_config_files``).
    :param content: Config file content to write.
    :param level: Precedence level (2 or 3) for the log message.
    :return: Path to the written file.
    """
    target = Path(spec.native_config_files[0])
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="UTF-8")
    logging.warning(
        "%s: wrote config to repo at %s (level %d). "
        "This tool has no --config flag; the file will be removed "
        "after the run.",
        spec.name,
        target.resolve(),
        level,
    )
    return target


def _deliver_config(
    spec: ToolSpec,
    content: str,
    level: int,
) -> tuple[list[str], Path | None]:
    """Deliver resolved config content via the appropriate mechanism.

    Tools with ``config_flag`` get a cached file passed via CLI. Tools with
    only ``native_config_files`` get a CWD file that must be cleaned up.

    :param spec: Tool specification.
    :param content: Config file content.
    :param level: Precedence level for logging.
    :return: Tuple of (extra CLI args, cleanup path or None).
    """
    if spec.config_flag:
        return _store_config_to_cache(spec, content)

    if spec.native_config_files:
        return [], _write_cwd_config(spec, content, level)

    msg = (
        f"{spec.name} has config content at level {level} but no config_flag "
        f"and no native_config_files to write to."
    )
    raise NotImplementedError(msg)


def resolve_config(
    spec: ToolSpec,
    tool_config: dict[str, Any] | None = None,
) -> tuple[list[str], Path | None]:
    """Resolve config for a tool using the 4-level precedence chain.

    :param spec: Tool specification.
    :param tool_config: Pre-loaded ``[tool.X]`` config dict. If ``None``,
        reads from ``pyproject.toml`` in the current directory.
    :return: Tuple of (extra CLI args for config, path to clean up).
        The path is ``None`` when no cleanup is needed (cache-based configs
        persist across runs). Non-``None`` paths are CWD files written for
        tools that have no ``--config`` flag.
    """
    # Level 1: Native config file exists in the repo.
    for config_file in spec.native_config_files:
        if Path(config_file).exists():
            logging.info(
                "%s: using native config file: %s (level 1).", spec.name, config_file
            )
            return [], None

    # Level 2: [tool.X] in pyproject.toml.
    if tool_config is None:
        tool_config = load_pyproject_tool_section(spec.name)

    if tool_config:
        if spec.reads_pyproject:
            logging.info(
                "%s: using [tool.%s] in pyproject.toml, read natively (level 2).",
                spec.name,
                spec.name,
            )
            return [], None

        content = spec.native_format.serialize(tool_config, tool_name=spec.name)
        logging.debug(
            "Translated [tool.%s] to %s:\n%s",
            spec.name,
            spec.native_format.value,
            content,
        )
        return _deliver_config(spec, content, level=2)

    # Level 3: Bundled default from repomatic/data/.
    if spec.default_config:
        with get_data_file_path(spec.default_config) as bundled_path:
            content = bundled_path.read_text(encoding="UTF-8")
        return _deliver_config(spec, content, level=3)

    # Level 4: Bare invocation.
    logging.info("%s: no config found, bare invocation (level 4).", spec.name)
    return [], None


# ---------------------------------------------------------------------------
# Binary download infrastructure
# ---------------------------------------------------------------------------


def _download_and_verify(
    url: str,
    expected_sha256: str | None,
    dest_path: Path,
    *,
    label: str | None = None,
) -> None:
    """Download a file and verify its SHA-256 checksum.

    Uses streaming download with chunked hash computation to handle large
    binaries without loading the entire file into memory. Shows a progress
    bar on interactive terminals when the server provides a
    ``Content-Length`` header.

    :param url: URL to download.
    :param expected_sha256: Expected lowercase hex SHA-256 digest.
        ``None`` skips verification (logs the computed digest for reference).
    :param dest_path: Where to write the downloaded file.
    :param label: Progress bar label. Defaults to the destination filename.
    :raises ValueError: If the checksum does not match.
    """
    request = Request(url)
    sha256 = hashlib.sha256()
    with urlopen(request) as response, dest_path.open("wb") as f:
        content_length = response.headers.get("Content-Length")
        total = int(content_length) if content_length else 0
        progress = (
            click.progressbar(
                length=total,
                label=label or dest_path.name,
                file=sys.stderr,
            )
            if total and sys.stderr.isatty()
            else nullcontext()
        )
        with progress as bar:
            while chunk := response.read(65536):
                f.write(chunk)
                sha256.update(chunk)
                if bar is not None:
                    bar.update(len(chunk))
    actual = sha256.hexdigest()
    if expected_sha256 is None:
        logging.info("SHA-256 of %s: %s (not verified).", url, actual)
        return
    if actual != expected_sha256:
        dest_path.unlink(missing_ok=True)
        msg = f"SHA-256 mismatch for {url}: expected {expected_sha256}, got {actual}"
        raise ValueError(msg)
    logging.debug("SHA-256 verified for %s: %s", url, actual)


def _check_member_safety(member_path: str) -> None:
    """Reject archive members with path traversal or absolute paths.

    :raises ValueError: If the member path is unsafe.
    """
    parts = PurePosixPath(member_path).parts
    if ".." in parts or member_path.startswith("/"):
        msg = f"Unsafe archive member path: {member_path}"
        raise ValueError(msg)


def _finalize_extracted(
    member_path: str,
    dest_dir: Path,
    target: str,
) -> Path:
    """Rename an extracted member to its final location and make executable.

    :param member_path: Archive member path as extracted.
    :param dest_dir: Directory the member was extracted into.
    :param target: Expected (stripped) filename.
    :return: Final path to the executable.
    """
    extracted = dest_dir / member_path
    final = dest_dir / PurePosixPath(target).name
    if extracted != final:
        extracted.rename(final)
    final.chmod(0o755)
    return final


def _extract_binary(
    archive_path: Path,
    spec: BinarySpec,
    dest_dir: Path,
    tool_name: str,
    archive_format: ArchiveFormat | None = None,
) -> Path:
    """Extract the tool executable from a downloaded archive.

    :param archive_path: Path to the downloaded archive file.
    :param spec: Binary specification with format and executable info.
    :param dest_dir: Directory to extract into.
    :param tool_name: Tool name, used as default for ``archive_executable``.
    :param archive_format: Override the spec's default archive format.
        Used by ``_install_binary`` to pass the per-platform format from
        ``BinarySpec.get_archive_format``.
    :return: Path to the extracted executable.
    :raises FileNotFoundError: If the executable is not found in the archive.
    """
    if archive_format is not None:
        fmt = archive_format
    elif isinstance(spec.archive_format, ArchiveFormat):
        fmt = spec.archive_format
    else:
        msg = "archive_format is required when spec.archive_format is a dict"
        raise TypeError(msg)
    executable = spec.archive_executable or tool_name

    if fmt == ArchiveFormat.RAW:
        dest = dest_dir / executable
        archive_path.rename(dest)
        dest.chmod(0o755)
        return dest

    if fmt == ArchiveFormat.ZIP:
        return _extract_from_zip(archive_path, spec, dest_dir, executable)

    return _extract_from_tar(archive_path, fmt, spec, dest_dir, executable)


def _extract_from_tar(
    archive_path: Path,
    fmt: ArchiveFormat,
    spec: BinarySpec,
    dest_dir: Path,
    executable: str,
) -> Path:
    """Extract a tool executable from a tar archive."""
    with tarfile.open(str(archive_path), fmt.tarfile_mode()) as tar:
        for member in tar.getmembers():
            parts = PurePosixPath(member.name).parts
            if len(parts) <= spec.strip_components:
                continue
            stripped = str(PurePosixPath(*parts[spec.strip_components :]))
            if stripped == executable:
                _check_member_safety(member.name)
                if sys.version_info >= (3, 12):
                    tar.extract(member, dest_dir, filter="data")
                else:
                    tar.extract(member, dest_dir)
                return _finalize_extracted(member.name, dest_dir, executable)

    msg = f"Executable {executable!r} not found in archive"
    raise FileNotFoundError(msg)


def _extract_from_zip(
    archive_path: Path,
    spec: BinarySpec,
    dest_dir: Path,
    executable: str,
) -> Path:
    """Extract a tool executable from a ZIP archive."""
    # Windows executables may have a .exe suffix inside the archive.
    targets = {executable, f"{executable}.exe"}

    with zipfile.ZipFile(archive_path) as zf:
        for info in zf.infolist():
            if info.is_dir():
                continue
            parts = PurePosixPath(info.filename).parts
            if len(parts) <= spec.strip_components:
                continue
            stripped = str(PurePosixPath(*parts[spec.strip_components :]))
            if stripped in targets:
                _check_member_safety(info.filename)
                zf.extract(info, dest_dir)
                return _finalize_extracted(info.filename, dest_dir, stripped)

    msg = f"Executable {executable!r} not found in archive"
    raise FileNotFoundError(msg)


def _compute_file_sha256(path: Path) -> str:
    """Compute the SHA-256 hex digest of a file.

    :param path: Path to the file.
    :return: Lowercase hex SHA-256 digest.
    """
    sha256 = hashlib.sha256()
    with path.open("rb") as f:
        while chunk := f.read(65536):
            sha256.update(chunk)
    return sha256.hexdigest()


def _binary_sidecar_path(binary_path: Path) -> Path:
    """Return the ``.sha256`` sidecar path for a cached binary.

    The sidecar stores the SHA-256 digest of the extracted binary, computed
    after a verified archive download. This is distinct from the archive
    checksum in the registry: the archive checksum defends against supply-chain
    tampering at download time, while the sidecar defends against local cache
    tampering between runs.
    """
    return binary_path.with_suffix(binary_path.suffix + ".sha256")


def _write_binary_sidecar(binary_path: Path) -> None:
    """Compute and write the SHA-256 sidecar for a cached binary.

    Called after a verified archive download + extraction + cache store.
    The sidecar is the trust anchor for subsequent cache hits.
    """
    digest = _compute_file_sha256(binary_path)
    sidecar = _binary_sidecar_path(binary_path)
    sidecar.write_text(digest, encoding="UTF-8")
    logging.debug("Wrote binary sidecar: %s (%s).", sidecar, digest)


def _verify_cached_binary(path: Path) -> bool:
    """Verify a cached binary against its ``.sha256`` sidecar.

    :param path: Path to the cached binary.
    :return: ``True`` if the sidecar exists and the digest matches.
    """
    sidecar = _binary_sidecar_path(path)
    if not sidecar.is_file():
        return False
    expected = sidecar.read_text(encoding="UTF-8").strip()
    return _compute_file_sha256(path) == expected


def _install_binary(
    spec: ToolSpec,
    tmp_dir: Path,
    skip_checksum: bool = False,
    no_cache: bool = False,
) -> Path:
    """Download, verify, and extract a binary tool.

    Two-layer integrity model:

    - **Archive checksum** (download time): the registry checksum is verified
      against the downloaded archive. This defends against supply-chain
      tampering and is auditable against the upstream release page.
    - **Binary sidecar** (cache hit): after a verified download, extraction,
      and cache store, a ``.sha256`` sidecar is written next to the cached
      binary. Subsequent cache hits verify the binary against this sidecar,
      defending against local cache tampering between runs.

    :param spec: Tool specification with ``binary`` set.
    :param tmp_dir: Temporary directory for download and extraction.
    :param skip_checksum: Skip SHA-256 verification when ``True``.
    :param no_cache: Bypass the cache entirely when ``True``.
    :return: Path to the ready-to-run executable.
    :raises RuntimeError: If no binary is available for the current platform.
    """
    binary = spec.binary
    assert binary is not None

    key = binary.resolve_platform()
    cache_key = BinarySpec.platform_cache_key(key)

    executable = binary.archive_executable or spec.name
    checksum = binary.checksums.get(key, "")

    # Check cache (unless --no-cache).
    if not no_cache:
        cached = get_cached_binary(spec.name, spec.version, cache_key, executable)
        if cached is not None:
            if skip_checksum:
                logging.info(
                    "Using cached %s %s for %s (checksum skipped).",
                    spec.name,
                    spec.version,
                    cache_key,
                )
                return cached
            if _verify_cached_binary(cached):
                logging.info(
                    "Using cached %s %s for %s (sidecar verified).",
                    spec.name,
                    spec.version,
                    cache_key,
                )
                return cached
            # Sidecar missing or digest mismatch: re-download from source.
            logging.warning(
                "Cached %s %s failed integrity check, re-downloading.",
                spec.name,
                spec.version,
            )
            cached.unlink(missing_ok=True)
            _binary_sidecar_path(cached).unlink(missing_ok=True)

    url = binary.urls[key].format(version=spec.version)

    # Derive archive filename from URL.
    archive_name = url.rsplit("/", 1)[-1]
    archive_path = tmp_dir / archive_name

    logging.info("Downloading %s %s for %s...", spec.name, spec.version, cache_key)
    if skip_checksum:
        logging.warning("Checksum verification skipped for %s.", spec.name)
    _download_and_verify(
        url,
        None if skip_checksum else checksum,
        archive_path,
        label=f"{spec.name} {spec.version}",
    )

    fmt = binary.get_archive_format(key)
    extracted = _extract_binary(archive_path, binary, tmp_dir, spec.name, fmt)

    # Store in cache for future use. Verify the cached copy is accessible
    # before returning it; fall back to the temp directory copy otherwise.
    # Docker-based CI runners (e.g., ubuntu-slim) can silently lose cached
    # files due to overlay filesystem or mount restrictions.
    if not no_cache:
        cached = store_binary(spec.name, spec.version, cache_key, extracted)
        if cached.is_file():
            _write_binary_sidecar(cached)
            return cached
        logging.warning(
            "Cached binary missing after store at %s, using temp path.",
            cached,
        )
    return extracted


@contextmanager
def binary_tool_context(
    name: str,
    no_cache: bool = False,
) -> Iterator[Path]:
    """Download a binary tool and yield its executable path.

    For tools invoked indirectly by repomatic commands (e.g., labelmaker
    called by ``sync-labels``) rather than via ``run_tool()``. Downloads
    once; the binary stays valid for the context's duration. On a cache hit
    the yielded path points to the cache and the staging directory is empty.

    :param name: Tool name (must be in ``TOOL_REGISTRY`` with ``binary`` set).
    :param no_cache: Bypass the binary cache when ``True``.
    :yields: Path to the ready-to-run executable.
    """
    spec = TOOL_REGISTRY[name]
    assert spec.binary is not None, f"{name} has no binary spec"
    with tempfile.TemporaryDirectory(prefix=f"repomatic-{name}-bin-") as bin_dir:
        yield _install_binary(spec, Path(bin_dir), no_cache=no_cache)


# ---------------------------------------------------------------------------
# Tool invocation
# ---------------------------------------------------------------------------


def _build_install_args(spec: ToolSpec) -> list[str]:
    """Build the command prefix for installing and running a tool."""
    package_pin = f"{spec.package or spec.name}=={spec.version}"
    executable = spec.executable or spec.name

    if spec.needs_venv:
        cmd = uv_cmd("run", frozen=True)
        cmd.extend(["--with", package_pin, "--", executable])
    else:
        cmd = uvx_cmd()
        for pkg in spec.with_packages:
            cmd.extend(["--with", pkg])
        cmd.extend(["--from", package_pin, executable])

    return cmd


def _splice_config_args(
    config_args: list[str],
    extra_args: Sequence[str],
    spec: ToolSpec,
) -> list[str]:
    """Combine config and extra args in the order the tool expects.

    When ``spec.config_after_subcommand`` is ``True`` and ``extra_args``
    starts with a subcommand name, config args are inserted after it::

        [subcommand] + config_args + [remaining extra_args]

    Otherwise config args come first (the default).
    """
    if spec.config_after_subcommand and config_args and extra_args:
        return [extra_args[0], *config_args, *extra_args[1:]]
    return [*config_args, *extra_args]


def run_tool(
    name: str,
    extra_args: Sequence[str] = (),
    version: str | None = None,
    checksum: str | None = None,
    skip_checksum: bool = False,
    no_cache: bool = False,
) -> int:
    """Run an external tool with managed config resolution.

    :param name: Tool name (must be in ``TOOL_REGISTRY``).
    :param extra_args: Extra arguments passed through to the tool.
    :param version: Override the pinned version.
    :param checksum: Override the SHA-256 checksum for the current platform.
    :param skip_checksum: Skip SHA-256 verification entirely.
    :param no_cache: Bypass the binary cache when ``True``.
    :return: The tool's exit code.
    """
    if name not in TOOL_REGISTRY:
        msg = (
            f"Unknown tool: {name!r}. "
            f"Available tools: {', '.join(sorted(TOOL_REGISTRY))}"
        )
        raise ValueError(msg)

    spec = TOOL_REGISTRY[name]

    # Apply CLI overrides to the frozen spec.
    if version:
        spec = replace(spec, version=version)
    if checksum and spec.binary:
        key = spec.binary.resolve_platform()
        new_checksums = {**spec.binary.checksums, key: checksum}
        spec = replace(spec, binary=replace(spec.binary, checksums=new_checksums))

    logging.info("Resolving config for %s %s...", spec.name, spec.version)
    config_args, tmp_path = resolve_config(spec)

    bin_dir = None
    try:
        # Build command prefix: binary download or uvx/uv-run.
        if spec.binary is not None:
            bin_dir = tempfile.TemporaryDirectory(
                prefix=f"repomatic-{name}-bin-",
            )
            try:
                bin_path = _install_binary(
                    spec,
                    Path(bin_dir.name),
                    skip_checksum,
                    no_cache=no_cache,
                )
            except RuntimeError as exc:
                import click

                raise click.ClickException(str(exc)) from exc
            cmd = [str(bin_path)]
        else:
            cmd = _build_install_args(spec)

        # Default flags (always applied).
        if spec.default_flags:
            cmd.extend(spec.default_flags)

        # CI output format flags.
        if spec.ci_flags and is_github_ci():
            cmd.extend(spec.ci_flags)

        # Computed parameters derived from project metadata.
        if spec.computed_params:
            from .metadata import Metadata

            cmd.extend(spec.computed_params(Metadata()))

        # Config args from resolution (cache path or empty).
        cmd.extend(_splice_config_args(config_args, extra_args, spec))

        # Ensure parent directories exist for output file paths.
        for i, arg in enumerate(extra_args):
            if arg == "--output" and i + 1 < len(extra_args):
                Path(extra_args[i + 1]).parent.mkdir(parents=True, exist_ok=True)

        logging.info("Running: %s", " ".join(cmd))
        result = subprocess.run(cmd, check=False)

        logging.info("%s exited with code %d.", spec.name, result.returncode)

        if result.returncode == 0 and spec.post_process:
            spec.post_process(extra_args)

        return result.returncode

    finally:
        if bin_dir is not None:
            bin_dir.cleanup()
        if tmp_path is not None:
            logging.debug("Cleaning up temp config: %s", tmp_path.resolve())
            tmp_path.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Diagnostics
# ---------------------------------------------------------------------------


def _detect_config_level(spec: ToolSpec) -> tuple[int, str]:
    """Detect which precedence level is active for a tool's config.

    Performs the same 4-level walk as :func:`resolve_config` but only
    detects the level without producing config content or CLI args.

    :return: ``(level, description)`` where level is 1-4 and description
        is a human-readable source label.
    """
    for config_file in spec.native_config_files:
        if Path(config_file).exists():
            return 1, config_file

    tool_config = load_pyproject_tool_section(spec.name)
    if tool_config:
        return 2, f"[tool.{spec.name}] in pyproject.toml"

    if spec.default_config:
        return 3, "bundled default"

    return 4, "(bare)"


def resolve_config_source(spec: ToolSpec) -> str:
    """Return a human-readable description of the active config source.

    Used by ``repomatic run --list`` to show which precedence level is active
    for each tool in the current repo.
    """
    return _detect_config_level(spec)[1]


def find_unmodified_configs() -> list[tuple[str, str]]:
    """Find native config files identical to their bundled defaults.

    Iterates over every tool in :data:`TOOL_REGISTRY` that has a
    ``default_config``.  For each, checks whether any of its
    ``native_config_files`` exists on disk and is content-identical
    to the bundled default after trailing-whitespace normalization.

    The normalization (``rstrip() + "\\n"``) matches the convention
    used by ``_init_config_files`` when writing files during ``init``.

    :return: List of ``(tool_name, relative_path)`` tuples for each
        unmodified file found.
    """
    unmodified: list[tuple[str, str]] = []

    for name, spec in sorted(TOOL_REGISTRY.items()):
        if not spec.default_config:
            continue

        with get_data_file_path(spec.default_config) as bundled_path:
            bundled = bundled_path.read_text(encoding="UTF-8").rstrip() + "\n"

        for config_file in spec.native_config_files:
            path = Path(config_file)
            if not path.exists():
                continue
            native = path.read_text(encoding="UTF-8").rstrip() + "\n"
            if native == bundled:
                unmodified.append((name, config_file))

    return unmodified
