flowchart LR
    repomatic[["`repomatic`"]]

    subgraph primary-deps [Primary dependencies]
        bump_my_version{{"`bump-my-version`"}}
        click_extra{{"`click-extra`"}}
        pydriller{{"`pydriller`"}}
        wcmatch{{"`wcmatch`"}}
        extra_platforms{{"`extra-platforms`"}}
        py_walk{{"`py-walk`"}}
        pyproject_metadata{{"`pyproject-metadata`"}}
        packaging{{"`packaging`"}}
        tomli{{"`tomli`"}}
        boltons{{"`boltons`"}}
        backports_strenum{{"`backports-strenum`"}}
        pyyaml{{"`pyyaml`"}}
    end

    typing_extensions(["`typing-extensions`"])
    pydantic(["`pydantic`"])
    click_0(["`click`"])
    httpx(["`httpx`"])
    requests(["`requests`"])
    rich_click(["`rich-click`"])
    anyio(["`anyio`"])
    pydantic_settings(["`pydantic-settings`"])
    rich(["`rich`"])
    certifi(["`certifi`"])
    cloup(["`cloup`"])
    colorama(["`colorama`"])
    exceptiongroup(["`exceptiongroup`"])
    httpcore(["`httpcore`"])
    idna(["`idna`"])
    lizard(["`lizard`"])
    pygments(["`pygments`"])
    typing_inspection(["`typing-inspection`"])
    gitdb(["`gitdb`"])
    gitpython(["`gitpython`"])
    markdown_it_py(["`markdown-it-py`"])
    prompt_toolkit(["`prompt-toolkit`"])
    pydantic_core(["`pydantic-core`"])
    questionary(["`questionary`"])
    tabulate(["`tabulate`"])
    wcwidth(["`wcwidth`"])
    annotated_types(["`annotated-types`"])
    bracex(["`bracex`"])
    charset_normalizer(["`charset-normalizer`"])
    deepmerge(["`deepmerge`"])
    distro(["`distro`"])
    h11(["`h11`"])
    mdurl(["`mdurl`"])
    pathspec(["`pathspec`"])
    python_dotenv(["`python-dotenv`"])
    pytz(["`pytz`"])
    sly(["`sly`"])
    smmap(["`smmap`"])
    tomlkit(["`tomlkit`"])
    types_pytz(["`types-pytz`"])
    urllib3(["`urllib3`"])

    subgraph grp_test [--group test]
        pytest{{"`pytest >=9`"}}
        pytest_cases{{"`pytest-cases >=3.9`"}}
        pytest_cov{{"`pytest-cov >=7`"}}
        coverage{{"`coverage >=7.11`"}}
        decopatch(["`decopatch`"])
        makefun(["`makefun`"])
        pluggy(["`pluggy`"])
        pytest_github_actions_annotate_failures{{"`pytest-github-actions-annotate-failures >=0.3`"}}
        pytest_randomly{{"`pytest-randomly >=4`"}}
        iniconfig(["`iniconfig`"])
    end

    subgraph grp_typing [--group typing]
        types_boltons{{"`types-boltons >=25.0.0.20250822`"}}
        types_pyyaml{{"`types-pyyaml >=6.0.12.9`"}}
    end

    repomatic ==>|" >=1.2.6 "| bump_my_version
    repomatic ==>|" >=7.5 "| click_extra
    repomatic ==>|" >=2.6 "| pydriller
    repomatic ==>|" >=25 "| packaging
    repomatic ==>|" >=2.3 "| tomli
    repomatic ==>|" >=10 "| wcmatch
    repomatic ==>|" >=8 "| extra_platforms
    repomatic ==>|" >=25 "| boltons
    repomatic ==>|" >=0.3.3 "| py_walk
    repomatic ==>|" >=0.9 "| pyproject_metadata
    repomatic ==>|" >=1.3.1 "| backports_strenum
    repomatic ==>|" >=6.0.3 "| pyyaml
    pytest ==> packaging
    pytest ==> tomli
    pytest --> colorama
    pytest --> exceptiongroup
    pytest --> pygments
    pytest --> pluggy
    pytest --> iniconfig
    bump_my_version --> pydantic
    bump_my_version --> click_0
    bump_my_version --> httpx
    bump_my_version --> rich_click
    bump_my_version --> pydantic_settings
    bump_my_version --> rich
    bump_my_version ==> wcmatch
    bump_my_version --> questionary
    bump_my_version --> tomlkit
    click_extra --> click_0
    click_extra --> requests
    click_extra ==> tomli
    click_extra ==> wcmatch
    click_extra --> cloup
    click_extra ==> extra_platforms
    click_extra ==> boltons
    click_extra --> tabulate
    click_extra --> deepmerge
    pydriller --> lizard
    pydriller --> gitpython
    pydriller --> pytz
    pydriller --> types_pytz
    pytest_cases ==> pytest
    pytest_cases ==> packaging
    pytest_cases --> decopatch
    pytest_cases --> makefun
    pytest_cov ==> pytest
    pytest_cov ==> coverage
    pytest_cov --> pluggy
    wcmatch --> bracex
    coverage ==> tomli
    extra_platforms --> distro
    py_walk --> sly
    pyproject_metadata ==> packaging
    pytest_github_actions_annotate_failures ==> pytest
    pytest_randomly ==> pytest
    pydantic --> typing_extensions
    pydantic --> typing_inspection
    pydantic --> pydantic_core
    pydantic --> annotated_types
    click_0 --> colorama
    httpx --> anyio
    httpx --> certifi
    httpx --> httpcore
    httpx --> idna
    requests --> certifi
    requests --> idna
    requests --> charset_normalizer
    requests --> urllib3
    rich_click --> typing_extensions
    rich_click --> click_0
    rich_click --> rich
    rich_click --> colorama
    pydantic_settings --> pydantic
    pydantic_settings --> typing_inspection
    pydantic_settings --> python_dotenv
    rich --> pygments
    rich --> markdown_it_py
    cloup --> typing_extensions
    cloup --> click_0
    exceptiongroup --> typing_extensions
    lizard --> pygments
    lizard --> pathspec
    decopatch --> makefun
    gitpython --> gitdb
    questionary --> prompt_toolkit
    tabulate --> wcwidth
    anyio --> typing_extensions
    anyio --> exceptiongroup
    anyio --> idna
    httpcore --> certifi
    httpcore --> h11
    typing_inspection --> typing_extensions
    gitdb --> smmap
    markdown_it_py --> mdurl
    prompt_toolkit --> wcwidth
    pydantic_core --> typing_extensions
    repomatic -.-> grp_test
    repomatic -.-> grp_typing

    click annotated_types "https://pypi.org/project/annotated-types/" _blank
    click anyio "https://pypi.org/project/anyio/" _blank
    click backports_strenum "https://pypi.org/project/backports-strenum/" _blank
    click boltons "https://pypi.org/project/boltons/" _blank
    click bracex "https://pypi.org/project/bracex/" _blank
    click bump_my_version "https://pypi.org/project/bump-my-version/" _blank
    click certifi "https://pypi.org/project/certifi/" _blank
    click charset_normalizer "https://pypi.org/project/charset-normalizer/" _blank
    click click_0 "https://pypi.org/project/click/" _blank
    click click_extra "https://pypi.org/project/click-extra/" _blank
    click cloup "https://pypi.org/project/cloup/" _blank
    click colorama "https://pypi.org/project/colorama/" _blank
    click coverage "https://pypi.org/project/coverage/" _blank
    click decopatch "https://pypi.org/project/decopatch/" _blank
    click deepmerge "https://pypi.org/project/deepmerge/" _blank
    click distro "https://pypi.org/project/distro/" _blank
    click exceptiongroup "https://pypi.org/project/exceptiongroup/" _blank
    click extra_platforms "https://pypi.org/project/extra-platforms/" _blank
    click gitdb "https://pypi.org/project/gitdb/" _blank
    click gitpython "https://pypi.org/project/gitpython/" _blank
    click h11 "https://pypi.org/project/h11/" _blank
    click httpcore "https://pypi.org/project/httpcore/" _blank
    click httpx "https://pypi.org/project/httpx/" _blank
    click idna "https://pypi.org/project/idna/" _blank
    click iniconfig "https://pypi.org/project/iniconfig/" _blank
    click lizard "https://pypi.org/project/lizard/" _blank
    click makefun "https://pypi.org/project/makefun/" _blank
    click markdown_it_py "https://pypi.org/project/markdown-it-py/" _blank
    click mdurl "https://pypi.org/project/mdurl/" _blank
    click packaging "https://pypi.org/project/packaging/" _blank
    click pathspec "https://pypi.org/project/pathspec/" _blank
    click pluggy "https://pypi.org/project/pluggy/" _blank
    click prompt_toolkit "https://pypi.org/project/prompt-toolkit/" _blank
    click py_walk "https://pypi.org/project/py-walk/" _blank
    click pydantic "https://pypi.org/project/pydantic/" _blank
    click pydantic_core "https://pypi.org/project/pydantic-core/" _blank
    click pydantic_settings "https://pypi.org/project/pydantic-settings/" _blank
    click pydriller "https://pypi.org/project/pydriller/" _blank
    click pygments "https://pypi.org/project/pygments/" _blank
    click pyproject_metadata "https://pypi.org/project/pyproject-metadata/" _blank
    click pytest "https://pypi.org/project/pytest/" _blank
    click pytest_cases "https://pypi.org/project/pytest-cases/" _blank
    click pytest_cov "https://pypi.org/project/pytest-cov/" _blank
    click pytest_github_actions_annotate_failures "https://pypi.org/project/pytest-github-actions-annotate-failures/" _blank
    click pytest_randomly "https://pypi.org/project/pytest-randomly/" _blank
    click python_dotenv "https://pypi.org/project/python-dotenv/" _blank
    click pytz "https://pypi.org/project/pytz/" _blank
    click pyyaml "https://pypi.org/project/pyyaml/" _blank
    click questionary "https://pypi.org/project/questionary/" _blank
    click repomatic "https://pypi.org/project/repomatic/" _blank
    click requests "https://pypi.org/project/requests/" _blank
    click rich "https://pypi.org/project/rich/" _blank
    click rich_click "https://pypi.org/project/rich-click/" _blank
    click sly "https://pypi.org/project/sly/" _blank
    click smmap "https://pypi.org/project/smmap/" _blank
    click tabulate "https://pypi.org/project/tabulate/" _blank
    click tomli "https://pypi.org/project/tomli/" _blank
    click tomlkit "https://pypi.org/project/tomlkit/" _blank
    click types_boltons "https://pypi.org/project/types-boltons/" _blank
    click types_pytz "https://pypi.org/project/types-pytz/" _blank
    click types_pyyaml "https://pypi.org/project/types-pyyaml/" _blank
    click typing_extensions "https://pypi.org/project/typing-extensions/" _blank
    click typing_inspection "https://pypi.org/project/typing-inspection/" _blank
    click urllib3 "https://pypi.org/project/urllib3/" _blank
    click wcmatch "https://pypi.org/project/wcmatch/" _blank
    click wcwidth "https://pypi.org/project/wcwidth/" _blank

    style repomatic stroke-width:3px
    style backports_strenum stroke-width:3px
    style boltons stroke-width:3px
    style bump_my_version stroke-width:3px
    style click_extra stroke-width:3px
    style coverage stroke-width:3px
    style extra_platforms stroke-width:3px
    style packaging stroke-width:3px
    style py_walk stroke-width:3px
    style pydriller stroke-width:3px
    style pyproject_metadata stroke-width:3px
    style pytest stroke-width:3px
    style pytest_cases stroke-width:3px
    style pytest_cov stroke-width:3px
    style pytest_github_actions_annotate_failures stroke-width:3px
    style pytest_randomly stroke-width:3px
    style pyyaml stroke-width:3px
    style tomli stroke-width:3px
    style types_boltons stroke-width:3px
    style types_pyyaml stroke-width:3px
    style wcmatch stroke-width:3px

    style primary-deps fill:#1565C020,stroke:#42A5F5
    style grp_test fill:#546E7A20,stroke:#90A4AE
    style grp_typing fill:#546E7A20,stroke:#90A4AE
