flowchart TD
    classDef missing stroke-dasharray: 5
    annotated-types["annotated-types\n0.7.0"]
    boltons["boltons\n24.1.0"]
    bracex["bracex\n2.5.post1"]
    bump-my-version["bump-my-version\n0.29.0"]
    certifi["certifi\n2024.12.14"]
    charset-normalizer["charset-normalizer\n3.4.1"]
    click-extra["click-extra\n4.11.7"]
    click_0["click\n8.1.8"]
    cloup["cloup\n3.0.5"]
    distro["distro\n1.9.0"]
    extra-platforms["extra-platforms\n1.6.0"]
    gha-utils["gha-utils\n4.10.0"]
    gitdb["gitdb\n4.0.12"]
    gitpython["GitPython\n3.1.44"]
    idna["idna\n3.10"]
    lizard["lizard\n1.17.13"]
    markdown-it-py["markdown-it-py\n3.0.0"]
    mdurl["mdurl\n0.1.2"]
    mergedeep["mergedeep\n1.3.4"]
    packaging["packaging\n24.2"]
    prompt-toolkit["prompt_toolkit\n3.0.48"]
    pydantic-core["pydantic_core\n2.27.2"]
    pydantic-settings["pydantic-settings\n2.7.1"]
    pydantic["pydantic\n2.10.4"]
    pydriller["PyDriller\n2.7"]
    pygments["Pygments\n2.18.0"]
    pyproject-metadata["pyproject-metadata\n0.9.0"]
    python-dotenv["python-dotenv\n1.0.1"]
    pytz["pytz\n2024.2"]
    pyyaml["PyYAML\n6.0.2"]
    questionary["questionary\n2.1.0"]
    requests["requests\n2.32.3"]
    rich-click["rich-click\n1.8.5"]
    rich["rich\n13.9.4"]
    smmap["smmap\n5.0.2"]
    tabulate["tabulate\n0.9.0"]
    tomlkit["tomlkit\n0.13.2"]
    types-pytz["types-pytz\n2024.2.0.20241221"]
    typing-extensions["typing_extensions\n4.12.2"]
    urllib3["urllib3\n2.3.0"]
    wcmatch["wcmatch\n10.0"]
    wcwidth["wcwidth\n0.2.13"]
    xmltodict["xmltodict\n0.14.2"]
    bump-my-version -- ">=2.0.0" --> pydantic
    bump-my-version -- ">=8.5.1" --> wcmatch
    bump-my-version -- "any" --> click_0
    bump-my-version -- "any" --> pydantic-settings
    bump-my-version -- "any" --> questionary
    bump-my-version -- "any" --> rich
    bump-my-version -- "any" --> rich-click
    bump-my-version -- "any" --> tomlkit
    click-extra -- "~=0.14.2" --> xmltodict
    click-extra -- "~=0.9" --> tabulate
    click-extra -- "~=1.3.4" --> mergedeep
    click-extra -- "~=1.6.0" --> extra-platforms
    click-extra -- "~=10.0" --> wcmatch
    click-extra -- "~=2.32.3" --> requests
    click-extra -- "~=24.1.0" --> boltons
    click-extra -- "~=3.0.5" --> cloup
    click-extra -- "~=6.0.0" --> pyyaml
    click-extra -- "~=8.1.4" --> click_0
    cloup -- ">=8.0,<9.0" --> click_0
    extra-platforms -- "~=1.9.0" --> distro
    extra-platforms -- "~=24.1.0" --> boltons
    gha-utils -- ">=0.21.0" --> bump-my-version
    gha-utils -- ">=24.0.0" --> boltons
    gha-utils -- ">=8.5" --> wcmatch
    gha-utils -- "~=0.9.0" --> pyproject-metadata
    gha-utils -- "~=2.6" --> pydriller
    gha-utils -- "~=24.1" --> packaging
    gha-utils -- "~=4.11.0" --> click-extra
    gitdb -- ">=3.0.1,<6" --> smmap
    gitpython -- ">=4.0.1,<5" --> gitdb
    lizard -- "any" --> pygments
    markdown-it-py -- "~=0.1" --> mdurl
    prompt-toolkit -- "any" --> wcwidth
    pydantic -- "==2.27.2" --> pydantic-core
    pydantic -- ">=0.6.0" --> annotated-types
    pydantic -- ">=4.12.2" --> typing-extensions
    pydantic-core -- ">=4.6.0,!=4.7.0" --> typing-extensions
    pydantic-settings -- ">=0.21.0" --> python-dotenv
    pydantic-settings -- ">=2.7.0" --> pydantic
    pydriller -- "any" --> gitpython
    pydriller -- "any" --> lizard
    pydriller -- "any" --> pytz
    pydriller -- "any" --> types-pytz
    pyproject-metadata -- ">=19.0" --> packaging
    questionary -- ">=2.0,<4.0" --> prompt-toolkit
    requests -- ">=1.21.1,<3" --> urllib3
    requests -- ">=2,<4" --> charset-normalizer
    requests -- ">=2.5,<4" --> idna
    requests -- ">=2017.4.17" --> certifi
    rich -- ">=2.13.0,<3.0.0" --> pygments
    rich -- ">=2.2.0" --> markdown-it-py
    rich-click -- ">=10.7" --> rich
    rich-click -- ">=4" --> typing-extensions
    rich-click -- ">=7" --> click_0
    wcmatch -- ">=2.1.1" --> bracex

