---
name: Labeller (file-based)
"on":
  workflow_call:
    inputs:
      extra-rules:
        required: false
        type: string
  pull_request_target:

jobs:

  labeller:
    name: Issue & PR labeller based on changed files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Download default rules
        run: >
          curl -fsSL --output ./.github/labeller-file-based.yaml
          https://raw.githubusercontent.com/kdeldycke/workflows/main/.github/labeller-file-based.yaml
      - name: Extend default rules
        if: ${{ inputs.extra-rules }}
        run: |
          tee -a ./.github/labeller-file-based.yaml <<-EOF
          ${{ inputs.extra-rules }}
          EOF
      - name: Print all rules
        run: |
          cat ./.github/labeller-file-based.yaml
      - name: Apply rules
        uses: actions/labeler@v3.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/labeller-file-based.yaml"
          sync-labels: true
