---
Name: Tag release

"on":
  pull_request:
    branches:
      - main
  types: [closed]

jobs:

  git-tag:
    if: ${{ github.head_ref == 'prepare-release' && github.event.pull_request.merged }}
    runs-on: ubuntu-20.04
    steps:
      - uses: crazy-max/ghaction-dump-context@v1.2.0
      - uses: actions/checkout@v2.4.0
      - name: Extract current version
        id: get_version
        # Docs: https://docs.github.com/en/actions/learn-github-actions
        # /workflow-commands-for-github-actions#setting-an-output-parameter
        run: >
          echo "::set-output name=CURRENT_VERSION::$(
          grep "current_version = " ./.bumpversion.cfg | cut -d ' ' -f 3 )"
      - name: Print current version
        run: >
          echo "Current version:
          ${{ steps.get_version.outputs.CURRENT_VERSION }}"
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: v${{ steps.get_version.outputs.CURRENT_VERSION }}
