---
# Copied from: rasa/dotfiles/.github/workflows/toc.yml
# EDIT THE ABOVE FILE, NOT THIS COPY, OR YOUR CHANGES WILL BE LOST!
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: toc

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - master # @TODO remove
    paths:
      - "**/*.md"
  push:
    paths:
      - "**/*.md"
  workflow_call:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# permissions: write-all

jobs:
  toc:
    name: toc
    runs-on: ubuntu-24.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    timeout-minutes: 5
    env:
      GH_TOC_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TOC_URL: https://raw.githubusercontent.com/ekalinin/github-markdown-toc/HEAD/gh-md-toc
    steps:
      - name: USE actions/checkout@v4.2.2
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1
          show-progress: false
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: RUN gh-md-toc
        run: |
          # RUN gh-md-toc
          mapfile -t < <(git ls-files '*.[Mm][Dd]')
          if ((${#MAPFILE[@]}==0)); then
            printf 'No .md files found in %s\n' "${PWD}"
            exit 0
          fi
          printf 'Downloading %s\n' "${TOC_URL}"
          curl -fsSL --output gh-md-toc "${TOC_URL}"
          chmod a+x gh-md-toc
          printf 'Processing %d .md files...\n' "${#MAPFILE[@]}"
          ./gh-md-toc --indent 0 --no-backup --hide-footer --skip-header "${MAPFILE[@]}"
          rm -f gh-md-toc

      - name: USE stefanzweifel/git-auto-commit-action@v5.1.0
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: "docs: auto update table-of-contents in *.md files"
